"""tables changed

Revision ID: 12e7bd0ef249
Revises: 379f6f1cf7e9
Create Date: 2022-07-03 17:51:30.634405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e7bd0ef249'
down_revision = '379f6f1cf7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Materials', sa.Column('Plant_id', sa.Integer(), nullable=True))
    op.add_column('Materials', sa.Column('Producer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Materials_Plant_id'), 'Materials', ['Plant_id'], unique=False)
    op.create_index(op.f('ix_Materials_Producer_id'), 'Materials', ['Producer_id'], unique=False)
    op.create_foreign_key(None, 'Materials', 'Plant', ['Producer_id'], ['id'])
    op.create_foreign_key(None, 'Materials', 'Plant', ['Plant_id'], ['id'])
    op.drop_column('Materials', 'Plant')
    op.drop_column('Materials', 'Producer')
    op.create_foreign_key(None, 'Shipto', 'Customers', ['SoldTo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shipto', type_='foreignkey')
    op.add_column('Materials', sa.Column('Producer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Materials', sa.Column('Plant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_index(op.f('ix_Materials_Producer_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Plant_id'), table_name='Materials')
    op.drop_column('Materials', 'Producer_id')
    op.drop_column('Materials', 'Plant_id')
    # ### end Alembic commands ###
