"""admin table created

Revision ID: 20c436feb618
Revises: 7cb4ea7699e6
Create Date: 2022-07-16 09:24:07.918454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c436feb618'
down_revision = '7cb4ea7699e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InvoiceLines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Invoice_id', sa.Integer(), nullable=False),
    sa.Column('Pricing_date', sa.Date(), nullable=False),
    sa.Column('GI_date', sa.Date(), nullable=False),
    sa.Column('Act_GI_date', sa.Date(), nullable=True),
    sa.Column('Material_id', sa.Integer(), nullable=False),
    sa.Column('Ord_Status_id', sa.Integer(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['Invoice_id'], ['Invoices.id'], ),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], ),
    sa.ForeignKeyConstraint(['Ord_Status_id'], ['OrderStatus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InvoiceLines_Invoice_id'), 'InvoiceLines', ['Invoice_id'], unique=False)
    op.drop_index('ix_InvoiceLunes_Invoice_id', table_name='InvoiceLunes')
    op.drop_table('InvoiceLunes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InvoiceLunes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"InvoiceLunes_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Pricing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('GI_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Act_GI_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Ord_Status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Qty', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Invoice_id'], ['Invoices.id'], name='InvoiceLunes_Invoice_id_fkey'),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], name='InvoiceLunes_Material_id_fkey'),
    sa.ForeignKeyConstraint(['Ord_Status_id'], ['OrderStatus.id'], name='InvoiceLunes_Ord_Status_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='InvoiceLunes_pkey')
    )
    op.create_index('ix_InvoiceLunes_Invoice_id', 'InvoiceLunes', ['Invoice_id'], unique=False)
    op.drop_index(op.f('ix_InvoiceLines_Invoice_id'), table_name='InvoiceLines')
    op.drop_table('InvoiceLines')
    # ### end Alembic commands ###
