"""product table changed

Revision ID: 255dbc3999b9
Revises: de60c2ab1b79
Create Date: 2022-06-19 12:26:09.275156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255dbc3999b9'
down_revision = 'de60c2ab1b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SalProducts_Sal_Prod_Code_key', 'SalProducts', type_='unique')
    op.create_index(op.f('ix_SalProducts_Sal_Prod_Code'), 'SalProducts', ['Sal_Prod_Code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SalProducts_Sal_Prod_Code'), table_name='SalProducts')
    op.create_unique_constraint('SalProducts_Sal_Prod_Code_key', 'SalProducts', ['Sal_Prod_Code'])
    # ### end Alembic commands ###
