"""tables are changed

Revision ID: 379f6f1cf7e9
Revises: 6350bbfc7885
Create Date: 2022-07-02 20:20:05.663506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f6f1cf7e9'
down_revision = '6350bbfc7885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ED',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.DateTime(), nullable=True),
    sa.Column('To', sa.DateTime(), nullable=True),
    sa.Column('Rate', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ED_From'), 'ED', ['From'], unique=True)
    op.create_index(op.f('ix_ED_To'), 'ED', ['To'], unique=True)
    op.add_column('Addresses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('BOs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Customers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('Customers', 'SoldTo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Customers', 'INN',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Customers', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Customers', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Customers', 'PayTerm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('LoB', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('Managers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Managers', 'STL_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Managers', 'LoB_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Materials', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('Materials', 'SalProduct_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Materials', 'BO_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Materials', 'Status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('PaymentTerms', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('ProdFamily', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('ProdFamily', 'SubClass_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('ProdSubClass', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('STLs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('SalProducts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('SalProducts', 'Family_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Shipto', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('Shipto', 'ShipTo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'SoldTo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'YFRP_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Status', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('YFRP', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('YFRP', 'YFRP',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.alter_column('YFRP', 'YFRP',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('YFRP', 'is_deleted')
    op.drop_column('Status', 'is_deleted')
    op.alter_column('Shipto', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'YFRP_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'SoldTo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'ShipTo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Shipto', 'is_deleted')
    op.alter_column('SalProducts', 'Family_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('SalProducts', 'is_deleted')
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('STLs', 'is_deleted')
    op.drop_column('ProdSubClass', 'is_deleted')
    op.alter_column('ProdFamily', 'SubClass_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ProdFamily', 'is_deleted')
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('PaymentTerms', 'is_deleted')
    op.alter_column('Materials', 'Status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Materials', 'BO_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Materials', 'SalProduct_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Materials', 'is_deleted')
    op.alter_column('Managers', 'LoB_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Managers', 'STL_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Managers', 'is_deleted')
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('LoB', 'is_deleted')
    op.alter_column('Customers', 'PayTerm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'INN',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Customers', 'SoldTo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Customers', 'is_deleted')
    op.drop_column('BOs', 'is_deleted')
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Addresses', 'is_deleted')
    op.drop_index(op.f('ix_ED_To'), table_name='ED')
    op.drop_index(op.f('ix_ED_From'), table_name='ED')
    op.drop_table('ED')
    # ### end Alembic commands ###
