"""fx tables added

Revision ID: 471c9ed3928d
Revises: 64c783881d2a
Create Date: 2022-07-06 09:03:40.498753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471c9ed3928d'
down_revision = '64c783881d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Curr_code', sa.String(), nullable=False),
    sa.Column('Curr_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Currency_Curr_code'), 'Currency', ['Curr_code'], unique=True)
    op.add_column('FX_rate', sa.Column('Curr_id', sa.Integer(), nullable=True))
    op.drop_index('ix_FX_rate_Curr_Name', table_name='FX_rate')
    op.create_index(op.f('ix_FX_rate_Curr_id'), 'FX_rate', ['Curr_id'], unique=False)
    op.create_foreign_key(None, 'FX_rate', 'Currency', ['Curr_id'], ['id'])
    op.drop_column('FX_rate', 'Curr_Name')
    op.drop_column('FX_rate', 'is_deleted')
    op.drop_column('FX_rate', 'FX_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FX_rate', sa.Column('FX_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('FX_rate', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('FX_rate', sa.Column('Curr_Name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'FX_rate', type_='foreignkey')
    op.drop_index(op.f('ix_FX_rate_Curr_id'), table_name='FX_rate')
    op.create_index('ix_FX_rate_Curr_Name', 'FX_rate', ['Curr_Name'], unique=False)
    op.drop_column('FX_rate', 'Curr_id')
    op.drop_index(op.f('ix_Currency_Curr_code'), table_name='Currency')
    op.drop_table('Currency')
    # ### end Alembic commands ###
