"""Order & Invoice tables changed

Revision ID: 4b03bbc5b2d6
Revises: f53dddcf5326
Create Date: 2022-07-17 23:33:17.133359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b03bbc5b2d6'
down_revision = 'f53dddcf5326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_open_order_lines_Delivry_id', table_name='open_order_lines')
    op.drop_index('ix_open_order_lines_Invoice_id', table_name='open_order_lines')
    op.drop_index('ix_open_order_lines_Order_id', table_name='open_order_lines')
    op.drop_table('open_order_lines')
    op.drop_index('ix_Deliveries_DeliveryN', table_name='Deliveries')
    op.drop_table('Deliveries')
    op.add_column('InvoiceType', sa.Column('OrderType', sa.String(), nullable=False))
    op.drop_index('ix_InvoiceType_Type_code', table_name='InvoiceType')
    op.create_index(op.f('ix_InvoiceType_OrderType'), 'InvoiceType', ['OrderType'], unique=True)
    op.drop_column('InvoiceType', 'Type_code')
    op.add_column('Invoices', sa.Column('Item', sa.Integer(), nullable=True))
    op.add_column('Invoices', sa.Column('Order_date', sa.Date(), nullable=True))
    op.add_column('Invoices', sa.Column('Price_date', sa.Date(), nullable=True))
    op.add_column('Invoices', sa.Column('Act_GI_date', sa.Date(), nullable=True))
    op.add_column('Invoices', sa.Column('Material_id', sa.Integer(), nullable=False))
    op.add_column('Invoices', sa.Column('Soldto_id', sa.Integer(), nullable=False))
    op.add_column('Invoices', sa.Column('Shipto_id', sa.Integer(), nullable=False))
    op.add_column('Invoices', sa.Column('Plant_id', sa.Integer(), nullable=False))
    op.add_column('Invoices', sa.Column('OrderN', sa.String(), nullable=True))
    op.add_column('Invoices', sa.Column('Order_type_id', sa.Integer(), nullable=True))
    op.add_column('Invoices', sa.Column('DeliveryN', sa.String(), nullable=True))
    op.add_column('Invoices', sa.Column('Proceeds', sa.Numeric(), nullable=True))
    op.add_column('Invoices', sa.Column('Qty', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'Invoices', 'Materials', ['Material_id'], ['id'])
    op.create_foreign_key(None, 'Invoices', 'OrderType', ['Order_type_id'], ['id'])
    op.create_foreign_key(None, 'Invoices', 'Shipto', ['Shipto_id'], ['id'])
    op.create_foreign_key(None, 'Invoices', 'Plant', ['Plant_id'], ['id'])
    op.create_foreign_key(None, 'Invoices', 'Customers', ['Soldto_id'], ['id'])
    op.add_column('Orders', sa.Column('OrderItem', sa.Integer(), nullable=True))
    op.add_column('Orders', sa.Column('LineItem', sa.Integer(), nullable=True))
    op.add_column('Orders', sa.Column('Price_date', sa.Date(), nullable=False))
    op.add_column('Orders', sa.Column('GI_date', sa.Date(), nullable=True))
    op.add_column('Orders', sa.Column('Act_GI_date', sa.Date(), nullable=True))
    op.add_column('Orders', sa.Column('Material_id', sa.Integer(), nullable=False))
    op.add_column('Orders', sa.Column('Ord_Status_id', sa.Integer(), nullable=True))
    op.add_column('Orders', sa.Column('DelivryN', sa.String(), nullable=True))
    op.add_column('Orders', sa.Column('LineQty', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'Orders', 'Materials', ['Material_id'], ['id'])
    op.create_foreign_key(None, 'Orders', 'OrderStatus', ['Ord_Status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_column('Orders', 'LineQty')
    op.drop_column('Orders', 'DelivryN')
    op.drop_column('Orders', 'Ord_Status_id')
    op.drop_column('Orders', 'Material_id')
    op.drop_column('Orders', 'Act_GI_date')
    op.drop_column('Orders', 'GI_date')
    op.drop_column('Orders', 'Price_date')
    op.drop_column('Orders', 'LineItem')
    op.drop_column('Orders', 'OrderItem')
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    op.drop_column('Invoices', 'Qty')
    op.drop_column('Invoices', 'Proceeds')
    op.drop_column('Invoices', 'DeliveryN')
    op.drop_column('Invoices', 'Order_type_id')
    op.drop_column('Invoices', 'OrderN')
    op.drop_column('Invoices', 'Plant_id')
    op.drop_column('Invoices', 'Shipto_id')
    op.drop_column('Invoices', 'Soldto_id')
    op.drop_column('Invoices', 'Material_id')
    op.drop_column('Invoices', 'Act_GI_date')
    op.drop_column('Invoices', 'Price_date')
    op.drop_column('Invoices', 'Order_date')
    op.drop_column('Invoices', 'Item')
    op.add_column('InvoiceType', sa.Column('Type_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_InvoiceType_OrderType'), table_name='InvoiceType')
    op.create_index('ix_InvoiceType_Type_code', 'InvoiceType', ['Type_code'], unique=False)
    op.drop_column('InvoiceType', 'OrderType')
    op.create_table('Deliveries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Deliveries_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('DeliveryN', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Deliveries_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_Deliveries_DeliveryN', 'Deliveries', ['DeliveryN'], unique=False)
    op.create_table('open_order_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LineItem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Pricing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('GI_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Act_GI_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Ord_Status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LineQty', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('Delivry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Delivry_id'], ['Deliveries.id'], name='open_order_lines_Delivry_id_fkey'),
    sa.ForeignKeyConstraint(['Invoice_id'], ['Invoices.id'], name='open_order_lines_Invoice_id_fkey'),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], name='open_order_lines_Material_id_fkey'),
    sa.ForeignKeyConstraint(['Ord_Status_id'], ['OrderStatus.id'], name='open_order_lines_Ord_Status_id_fkey'),
    sa.ForeignKeyConstraint(['Order_id'], ['Orders.id'], name='open_order_lines_Order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='open_order_lines_pkey')
    )
    op.create_index('ix_open_order_lines_Order_id', 'open_order_lines', ['Order_id'], unique=False)
    op.create_index('ix_open_order_lines_Invoice_id', 'open_order_lines', ['Invoice_id'], unique=False)
    op.create_index('ix_open_order_lines_Delivry_id', 'open_order_lines', ['Delivry_id'], unique=False)
    # ### end Alembic commands ###
