"""tables changed

Revision ID: 528c503903c9
Revises: 255dbc3999b9
Create Date: 2022-06-24 22:44:13.588893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '528c503903c9'
down_revision = '255dbc3999b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Customers_STL_id', table_name='Customers')
    op.drop_constraint('Customers_STL_id_fkey', 'Customers', type_='foreignkey')
    op.drop_column('Customers', 'STL_id')
    op.drop_index('ix_Materials_Family_id', table_name='Materials')
    op.drop_index('ix_Materials_SubClass_id', table_name='Materials')
    op.drop_constraint('Materials_Family_id_fkey', 'Materials', type_='foreignkey')
    op.drop_constraint('Materials_SubClass_id_fkey', 'Materials', type_='foreignkey')
    op.drop_column('Materials', 'SubClass_id')
    op.drop_column('Materials', 'Family_id')
    op.drop_index('ix_SalProducts_SubClass_id', table_name='SalProducts')
    op.drop_constraint('SalProducts_SubClass_id_fkey', 'SalProducts', type_='foreignkey')
    op.drop_column('SalProducts', 'SubClass_id')
    op.drop_index('ix_Shipto_LoB_id', table_name='Shipto')
    op.drop_index('ix_Shipto_STL_id', table_name='Shipto')
    op.drop_constraint('Shipto_STL_id_fkey', 'Shipto', type_='foreignkey')
    op.drop_constraint('Shipto_LoB_id_fkey', 'Shipto', type_='foreignkey')
    op.drop_column('Shipto', 'LoB_id')
    op.drop_column('Shipto', 'STL_id')
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_visit', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'active')
    op.drop_column('users', 'last_visit')
    op.drop_column('users', 'update_on')
    op.drop_column('users', 'created_on')
    op.add_column('Shipto', sa.Column('STL_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shipto', sa.Column('LoB_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Shipto_LoB_id_fkey', 'Shipto', 'LoB', ['LoB_id'], ['id'])
    op.create_foreign_key('Shipto_STL_id_fkey', 'Shipto', 'STLs', ['STL_id'], ['id'])
    op.create_index('ix_Shipto_STL_id', 'Shipto', ['STL_id'], unique=False)
    op.create_index('ix_Shipto_LoB_id', 'Shipto', ['LoB_id'], unique=False)
    op.add_column('SalProducts', sa.Column('SubClass_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('SalProducts_SubClass_id_fkey', 'SalProducts', 'ProdSubClass', ['SubClass_id'], ['id'])
    op.create_index('ix_SalProducts_SubClass_id', 'SalProducts', ['SubClass_id'], unique=False)
    op.add_column('Materials', sa.Column('Family_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Materials', sa.Column('SubClass_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Materials_SubClass_id_fkey', 'Materials', 'ProdSubClass', ['SubClass_id'], ['id'])
    op.create_foreign_key('Materials_Family_id_fkey', 'Materials', 'ProdFamily', ['Family_id'], ['id'])
    op.create_index('ix_Materials_SubClass_id', 'Materials', ['SubClass_id'], unique=False)
    op.create_index('ix_Materials_Family_id', 'Materials', ['Family_id'], unique=False)
    op.add_column('Customers', sa.Column('STL_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Customers_STL_id_fkey', 'Customers', 'STLs', ['STL_id'], ['id'])
    op.create_index('ix_Customers_STL_id', 'Customers', ['STL_id'], unique=False)
    # ### end Alembic commands ###
