"""change Managers

Revision ID: 6350bbfc7885
Revises: eeae6bb9eac5
Create Date: 2022-06-26 18:38:25.066240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6350bbfc7885'
down_revision = 'eeae6bb9eac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'PayTerm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Managers', 'STL_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Managers', 'LoB_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('Managers_STL_id_fkey', 'Managers', type_='foreignkey')
    op.drop_constraint('Managers_LoB_id_fkey', 'Managers', type_='foreignkey')
    op.create_foreign_key(None, 'Managers', 'STLs', ['STL_id'], ['id'])
    op.create_foreign_key(None, 'Managers', 'LoB', ['LoB_id'], ['id'])
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Shipto', 'SoldTo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'YFRP_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shipto', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shipto', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'YFRP_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'SoldTo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'Managers', type_='foreignkey')
    op.drop_constraint(None, 'Managers', type_='foreignkey')
    op.create_foreign_key('Managers_LoB_id_fkey', 'Managers', 'LoB', ['LoB_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('Managers_STL_id_fkey', 'Managers', 'STLs', ['STL_id'], ['id'], ondelete='SET NULL')
    op.alter_column('Managers', 'LoB_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Managers', 'STL_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Customers', 'PayTerm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Customers', 'Addr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Customers', 'AM_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
