"""user table - comp_id added

Revision ID: 64c783881d2a
Revises: f3537ddb8fc9
Create Date: 2022-07-03 19:02:10.394646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c783881d2a'
down_revision = 'f3537ddb8fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Customers', 'SoldTo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Managers', 'AM_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Shipto', 'ShipTo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('YFRP', 'YFRP',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('comp_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_comp_id'), 'users', ['comp_id'], unique=False)
    op.create_foreign_key(None, 'users', 'Customers', ['comp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_comp_id'), table_name='users')
    op.drop_column('users', 'comp_id')
    op.alter_column('YFRP', 'YFRP',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shipto', 'ShipTo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('STLs', 'STL',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PaymentTerms', 'Pay_term',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Managers', 'AM_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Managers', 'Sales_Grp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('LoB', 'LoB',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Customers', 'SoldTo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Addresses', 'Address_Code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
