"""tables changed

Revision ID: 8db4e1e6c5d6
Revises: f221f1a79f16
Create Date: 2022-06-24 23:24:13.619714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db4e1e6c5d6'
down_revision = 'f221f1a79f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
