"""tables changed

Revision ID: 93452f577061
Revises: a4e8774dc28e
Create Date: 2022-06-13 10:40:20.612669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93452f577061'
down_revision = 'a4e8774dc28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_STLs_LoB_id', table_name='STLs')
    op.drop_constraint('STLs_LoB_id_fkey', 'STLs', type_='foreignkey')
    op.drop_column('STLs', 'LoB_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('STLs', sa.Column('LoB_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('STLs_LoB_id_fkey', 'STLs', 'LoB', ['LoB_id'], ['id'])
    op.create_index('ix_STLs_LoB_id', 'STLs', ['LoB_id'], unique=False)
    # ### end Alembic commands ###
