"""update tables

Revision ID: 96ceb121c304
Revises: 
Create Date: 2022-06-12 23:47:02.916152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ceb121c304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Materials', sa.Column('SalProduct_id', sa.Integer(), nullable=False))
    op.add_column('Materials', sa.Column('Family_id', sa.Integer(), nullable=False))
    op.add_column('Materials', sa.Column('SubClass_id', sa.Integer(), nullable=False))
    op.add_column('Materials', sa.Column('BO_id', sa.Integer(), nullable=False))
    op.add_column('Materials', sa.Column('Status_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Materials_BO_id'), 'Materials', ['BO_id'], unique=False)
    op.create_index(op.f('ix_Materials_Family_id'), 'Materials', ['Family_id'], unique=False)
    op.create_index(op.f('ix_Materials_SalProduct_id'), 'Materials', ['SalProduct_id'], unique=False)
    op.create_index(op.f('ix_Materials_Status_id'), 'Materials', ['Status_id'], unique=False)
    op.create_index(op.f('ix_Materials_SubClass_id'), 'Materials', ['SubClass_id'], unique=False)
    op.create_foreign_key(None, 'Materials', 'ProdFamily', ['Family_id'], ['id'])
    op.create_foreign_key(None, 'Materials', 'SalProducts', ['SalProduct_id'], ['id'])
    op.create_foreign_key(None, 'Materials', 'Status', ['Status_id'], ['id'])
    op.create_foreign_key(None, 'Materials', 'BOs', ['BO_id'], ['id'])
    op.create_foreign_key(None, 'Materials', 'ProdSubClass', ['SubClass_id'], ['id'])
    op.add_column('ProdFamily', sa.Column('SubClass_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ProdFamily_SubClass_id'), 'ProdFamily', ['SubClass_id'], unique=False)
    op.create_foreign_key(None, 'ProdFamily', 'ProdSubClass', ['SubClass_id'], ['id'])
    op.add_column('SalProducts', sa.Column('Family_id', sa.Integer(), nullable=False))
    op.add_column('SalProducts', sa.Column('SubClass_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_SalProducts_Family_id'), 'SalProducts', ['Family_id'], unique=False)
    op.create_index(op.f('ix_SalProducts_SubClass_id'), 'SalProducts', ['SubClass_id'], unique=False)
    op.create_foreign_key(None, 'SalProducts', 'ProdSubClass', ['SubClass_id'], ['id'])
    op.create_foreign_key(None, 'SalProducts', 'ProdFamily', ['Family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SalProducts', type_='foreignkey')
    op.drop_constraint(None, 'SalProducts', type_='foreignkey')
    op.drop_index(op.f('ix_SalProducts_SubClass_id'), table_name='SalProducts')
    op.drop_index(op.f('ix_SalProducts_Family_id'), table_name='SalProducts')
    op.drop_column('SalProducts', 'SubClass_id')
    op.drop_column('SalProducts', 'Family_id')
    op.drop_constraint(None, 'ProdFamily', type_='foreignkey')
    op.drop_index(op.f('ix_ProdFamily_SubClass_id'), table_name='ProdFamily')
    op.drop_column('ProdFamily', 'SubClass_id')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_constraint(None, 'Materials', type_='foreignkey')
    op.drop_index(op.f('ix_Materials_SubClass_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Status_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_SalProduct_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Family_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_BO_id'), table_name='Materials')
    op.drop_column('Materials', 'Status_id')
    op.drop_column('Materials', 'BO_id')
    op.drop_column('Materials', 'SubClass_id')
    op.drop_column('Materials', 'Family_id')
    op.drop_column('Materials', 'SalProduct_id')
    # ### end Alembic commands ###
