"""price table created

Revision ID: a4d0f5361659
Revises: 471c9ed3928d
Create Date: 2022-07-08 22:22:13.835584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d0f5361659'
down_revision = '471c9ed3928d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PriceHierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('PriceTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TabN', sa.String(), nullable=False),
    sa.Column('Tab_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('TabN')
    )
    op.create_table('PriceType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('Type_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Type')
    )
    op.create_table('Prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Table_id', sa.Integer(), nullable=False),
    sa.Column('PriceType_id', sa.Integer(), nullable=False),
    sa.Column('ValidFrom', sa.Date(), nullable=False),
    sa.Column('ValidTo', sa.Date(), nullable=False),
    sa.Column('Hier_id', sa.Integer(), nullable=True),
    sa.Column('Soldto_id', sa.Integer(), nullable=True),
    sa.Column('Shipto_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Numeric(), nullable=True),
    sa.Column('PriceCurr', sa.String(), nullable=False),
    sa.Column('PricingUnit', sa.Integer(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Hier_id'], ['PriceHierarchy.id'], ),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], ),
    sa.ForeignKeyConstraint(['PriceType_id'], ['PriceType.id'], ),
    sa.ForeignKeyConstraint(['Shipto_id'], ['Shipto.id'], ),
    sa.ForeignKeyConstraint(['Soldto_id'], ['Customers.id'], ),
    sa.ForeignKeyConstraint(['Table_id'], ['PriceTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Customers', sa.Column('PriceHier_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Customers_PriceHier_id'), 'Customers', ['PriceHier_id'], unique=False)
    op.create_foreign_key(None, 'Customers', 'PriceHierarchy', ['PriceHier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_index(op.f('ix_Customers_PriceHier_id'), table_name='Customers')
    op.drop_column('Customers', 'PriceHier_id')
    op.drop_table('Prices')
    op.drop_table('PriceType')
    op.drop_table('PriceTable')
    op.drop_table('PriceHierarchy')
    # ### end Alembic commands ###
