"""tables changed

Revision ID: a4e8774dc28e
Revises: 96ceb121c304
Create Date: 2022-06-13 10:38:13.797877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e8774dc28e'
down_revision = '96ceb121c304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Address_Code', sa.Integer(), nullable=True),
    sa.Column('Region', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('Postal_Code', sa.Integer(), nullable=True),
    sa.Column('Street', sa.String(), nullable=True),
    sa.Column('House', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Addresses_Address_Code'), 'Addresses', ['Address_Code'], unique=True)
    op.drop_index('ix_Delivery_Addresses_Address_Code', table_name='Delivery_Addresses')
    op.drop_index('ix_Delivery_Addresses_SoldTo_id', table_name='Delivery_Addresses')
    op.drop_table('Delivery_Addresses')
    op.drop_index('ix_Customers_AM_id', table_name='Customers')
    op.drop_index('ix_Customers_LoB_id', table_name='Customers')
    op.drop_index('ix_Customers_STL_id', table_name='Customers')
    op.drop_index('ix_Customers_ShipTo', table_name='Customers')
    op.drop_constraint('Customers_LoB_id_fkey', 'Customers', type_='foreignkey')
    op.drop_constraint('Customers_AM_id_fkey', 'Customers', type_='foreignkey')
    op.drop_constraint('Customers_STL_id_fkey', 'Customers', type_='foreignkey')
    op.drop_column('Customers', 'LoB_id')
    op.drop_column('Customers', 'STL_id')
    op.drop_column('Customers', 'POD')
    op.drop_column('Customers', 'ShipTo')
    op.drop_column('Customers', 'YFRP')
    op.drop_column('Customers', 'AM_id')
    op.add_column('Shipto', sa.Column('POD', sa.String(), nullable=True))
    op.add_column('Shipto', sa.Column('AM_id', sa.Integer(), nullable=False))
    op.add_column('Shipto', sa.Column('STL_id', sa.Integer(), nullable=False))
    op.add_column('Shipto', sa.Column('LoB_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Shipto_AM_id'), 'Shipto', ['AM_id'], unique=False)
    op.create_index(op.f('ix_Shipto_LoB_id'), 'Shipto', ['LoB_id'], unique=False)
    op.create_index(op.f('ix_Shipto_STL_id'), 'Shipto', ['STL_id'], unique=False)
    op.create_foreign_key(None, 'Shipto', 'LoB', ['LoB_id'], ['id'])
    op.create_foreign_key(None, 'Shipto', 'STLs', ['STL_id'], ['id'])
    op.create_foreign_key(None, 'Shipto', 'Managers', ['AM_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shipto', type_='foreignkey')
    op.drop_constraint(None, 'Shipto', type_='foreignkey')
    op.drop_constraint(None, 'Shipto', type_='foreignkey')
    op.drop_index(op.f('ix_Shipto_STL_id'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_LoB_id'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_AM_id'), table_name='Shipto')
    op.drop_column('Shipto', 'LoB_id')
    op.drop_column('Shipto', 'STL_id')
    op.drop_column('Shipto', 'AM_id')
    op.drop_column('Shipto', 'POD')
    op.add_column('Customers', sa.Column('AM_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Customers', sa.Column('YFRP', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Customers', sa.Column('ShipTo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Customers', sa.Column('POD', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Customers', sa.Column('STL_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Customers', sa.Column('LoB_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Customers_STL_id_fkey', 'Customers', 'STLs', ['STL_id'], ['id'])
    op.create_foreign_key('Customers_AM_id_fkey', 'Customers', 'Managers', ['AM_id'], ['id'])
    op.create_foreign_key('Customers_LoB_id_fkey', 'Customers', 'LoB', ['LoB_id'], ['id'])
    op.create_index('ix_Customers_ShipTo', 'Customers', ['ShipTo'], unique=False)
    op.create_index('ix_Customers_STL_id', 'Customers', ['STL_id'], unique=False)
    op.create_index('ix_Customers_LoB_id', 'Customers', ['LoB_id'], unique=False)
    op.create_index('ix_Customers_AM_id', 'Customers', ['AM_id'], unique=False)
    op.create_table('Delivery_Addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Delivery_Addresses_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Address_Code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('City', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Postal_Code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('House', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('SoldTo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['SoldTo_id'], ['Customers.id'], name='Delivery_Addresses_SoldTo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Delivery_Addresses_pkey')
    )
    op.create_index('ix_Delivery_Addresses_SoldTo_id', 'Delivery_Addresses', ['SoldTo_id'], unique=False)
    op.create_index('ix_Delivery_Addresses_Address_Code', 'Delivery_Addresses', ['Address_Code'], unique=False)
    op.drop_index(op.f('ix_Addresses_Address_Code'), table_name='Addresses')
    op.drop_table('Addresses')
    # ### end Alembic commands ###
