"""tables changed

Revision ID: af302c659272
Revises: 93452f577061
Create Date: 2022-06-13 10:43:18.509613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af302c659272'
down_revision = '93452f577061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipto', sa.Column('Addr_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Shipto_Addr_id'), 'Shipto', ['Addr_id'], unique=False)
    op.create_foreign_key(None, 'Shipto', 'Addresses', ['Addr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shipto', type_='foreignkey')
    op.drop_index(op.f('ix_Shipto_Addr_id'), table_name='Shipto')
    op.drop_column('Shipto', 'Addr_id')
    # ### end Alembic commands ###
