"""tables created

Revision ID: c0a2fd71c0ea
Revises: 
Create Date: 2022-07-16 09:00:43.752047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a2fd71c0ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Address_Code', sa.Integer(), nullable=False),
    sa.Column('Region', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('Postal_Code', sa.Integer(), nullable=True),
    sa.Column('Street', sa.String(), nullable=True),
    sa.Column('House', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Addresses_Address_Code'), 'Addresses', ['Address_Code'], unique=True)
    op.create_table('BOs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BO_type', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Curr_code', sa.String(), nullable=False),
    sa.Column('Curr_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Currency_Curr_code'), 'Currency', ['Curr_code'], unique=True)
    op.create_table('Deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DeliveryN', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Deliveries_DeliveryN'), 'Deliveries', ['DeliveryN'], unique=True)
    op.create_table('ED',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('From', sa.Date(), nullable=False),
    sa.Column('To', sa.Date(), nullable=True),
    sa.Column('Rate', sa.Numeric(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ED_From'), 'ED', ['From'], unique=True)
    op.create_index(op.f('ix_ED_To'), 'ED', ['To'], unique=True)
    op.create_table('InvoiceType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type_code', sa.String(), nullable=False),
    sa.Column('Type_Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InvoiceType_Type_code'), 'InvoiceType', ['Type_code'], unique=True)
    op.create_table('LoB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('LoB', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LoB_LoB'), 'LoB', ['LoB'], unique=True)
    op.create_table('OrderStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Ord_Status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Ord_Status')
    )
    op.create_table('OrderType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type_code', sa.String(), nullable=False),
    sa.Column('Type_Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OrderType_Type_code'), 'OrderType', ['Type_code'], unique=True)
    op.create_table('PaymentTerms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pay_term', sa.String(), nullable=False),
    sa.Column('PT_description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PaymentTerms_Pay_term'), 'PaymentTerms', ['Pay_term'], unique=True)
    op.create_table('Plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Plant_Code', sa.String(), nullable=False),
    sa.Column('Plant_Name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Plant_Code')
    )
    op.create_table('PriceHierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('PriceTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TabN', sa.Integer(), nullable=False),
    sa.Column('Tab_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('TabN')
    )
    op.create_table('PriceType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('Type_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Type')
    )
    op.create_table('ProdSubClass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sub_Class', sa.Integer(), nullable=False),
    sa.Column('Sub_Class_Name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProdSubClass_Sub_Class'), 'ProdSubClass', ['Sub_Class'], unique=True)
    op.create_table('Producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Producer_Code', sa.String(), nullable=False),
    sa.Column('Producer_Name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Producer_Code')
    )
    op.create_table('STLs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('STL', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_STLs_STL'), 'STLs', ['STL'], unique=True)
    op.create_table('Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Status_code', sa.Integer(), nullable=False),
    sa.Column('Status_descr', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Status_Status_code'), 'Status', ['Status_code'], unique=True)
    op.create_table('FX_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FX_date', sa.Date(), nullable=True),
    sa.Column('Curr_id', sa.Integer(), nullable=True),
    sa.Column('Nominal', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['Curr_id'], ['Currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FX_rate_Curr_id'), 'FX_rate', ['Curr_id'], unique=False)
    op.create_index(op.f('ix_FX_rate_FX_date'), 'FX_rate', ['FX_date'], unique=False)
    op.create_table('Managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sales_Grp', sa.String(), nullable=False),
    sa.Column('AM_name', sa.String(), nullable=False),
    sa.Column('SO_code', sa.String(), nullable=True),
    sa.Column('STL_id', sa.Integer(), nullable=True),
    sa.Column('LoB_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['LoB_id'], ['LoB.id'], ),
    sa.ForeignKeyConstraint(['STL_id'], ['STLs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Managers_LoB_id'), 'Managers', ['LoB_id'], unique=False)
    op.create_index(op.f('ix_Managers_STL_id'), 'Managers', ['STL_id'], unique=False)
    op.create_index(op.f('ix_Managers_Sales_Grp'), 'Managers', ['Sales_Grp'], unique=True)
    op.create_table('ProdFamily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Family_Code', sa.String(), nullable=False),
    sa.Column('Family_Name', sa.String(), nullable=True),
    sa.Column('SubClass_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['SubClass_id'], ['ProdSubClass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProdFamily_Family_Code'), 'ProdFamily', ['Family_Code'], unique=True)
    op.create_index(op.f('ix_ProdFamily_SubClass_id'), 'ProdFamily', ['SubClass_id'], unique=False)
    op.create_table('YFRP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YFRP', sa.Integer(), nullable=False),
    sa.Column('YFRP_Name', sa.String(), nullable=True),
    sa.Column('Addr_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Addr_id'], ['Addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_YFRP_Addr_id'), 'YFRP', ['Addr_id'], unique=False)
    op.create_index(op.f('ix_YFRP_YFRP'), 'YFRP', ['YFRP'], unique=True)
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SoldTo', sa.Integer(), nullable=False),
    sa.Column('SoldTo_Name', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('KPP', sa.String(), nullable=True),
    sa.Column('AM_id', sa.Integer(), nullable=True),
    sa.Column('Addr_id', sa.Integer(), nullable=True),
    sa.Column('PayTerm_id', sa.Integer(), nullable=True),
    sa.Column('PriceHier_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AM_id'], ['Managers.id'], ),
    sa.ForeignKeyConstraint(['Addr_id'], ['Addresses.id'], ),
    sa.ForeignKeyConstraint(['PayTerm_id'], ['PaymentTerms.id'], ),
    sa.ForeignKeyConstraint(['PriceHier_id'], ['PriceHierarchy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Customers_AM_id'), 'Customers', ['AM_id'], unique=False)
    op.create_index(op.f('ix_Customers_Addr_id'), 'Customers', ['Addr_id'], unique=False)
    op.create_index(op.f('ix_Customers_PayTerm_id'), 'Customers', ['PayTerm_id'], unique=False)
    op.create_index(op.f('ix_Customers_PriceHier_id'), 'Customers', ['PriceHier_id'], unique=False)
    op.create_index(op.f('ix_Customers_SoldTo'), 'Customers', ['SoldTo'], unique=True)
    op.create_table('SalProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sal_Prod_Code', sa.String(), nullable=False),
    sa.Column('Sal_Prod_Name', sa.String(), nullable=True),
    sa.Column('Family_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Family_id'], ['ProdFamily.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SalProducts_Family_id'), 'SalProducts', ['Family_id'], unique=False)
    op.create_index(op.f('ix_SalProducts_Sal_Prod_Code'), 'SalProducts', ['Sal_Prod_Code'], unique=True)
    op.create_table('Materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Material_code', sa.String(), nullable=False),
    sa.Column('Material_Name', sa.String(), nullable=True),
    sa.Column('LoB', sa.String(), nullable=True),
    sa.Column('Pack_Vol', sa.Numeric(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('BO_Location', sa.String(), nullable=True),
    sa.Column('Production', sa.String(), nullable=True),
    sa.Column('Density', sa.Numeric(), nullable=True),
    sa.Column('Net_Weight', sa.Numeric(), nullable=True),
    sa.Column('ED_type', sa.String(), nullable=True),
    sa.Column('Pack_type', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('SalProduct_id', sa.Integer(), nullable=True),
    sa.Column('BO_id', sa.Integer(), nullable=True),
    sa.Column('Status_id', sa.Integer(), nullable=True),
    sa.Column('Plant_id', sa.Integer(), nullable=True),
    sa.Column('Producer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BO_id'], ['BOs.id'], ),
    sa.ForeignKeyConstraint(['Plant_id'], ['Plant.id'], ),
    sa.ForeignKeyConstraint(['Producer_id'], ['Producer.id'], ),
    sa.ForeignKeyConstraint(['SalProduct_id'], ['SalProducts.id'], ),
    sa.ForeignKeyConstraint(['Status_id'], ['Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Materials_BO_id'), 'Materials', ['BO_id'], unique=False)
    op.create_index(op.f('ix_Materials_Material_code'), 'Materials', ['Material_code'], unique=True)
    op.create_index(op.f('ix_Materials_Plant_id'), 'Materials', ['Plant_id'], unique=False)
    op.create_index(op.f('ix_Materials_Producer_id'), 'Materials', ['Producer_id'], unique=False)
    op.create_index(op.f('ix_Materials_SalProduct_id'), 'Materials', ['SalProduct_id'], unique=False)
    op.create_index(op.f('ix_Materials_Status_id'), 'Materials', ['Status_id'], unique=False)
    op.create_table('Shipto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ShipTo', sa.Integer(), nullable=False),
    sa.Column('ShipTo_Name', sa.String(), nullable=True),
    sa.Column('POD', sa.String(), nullable=True),
    sa.Column('SoldTo_id', sa.Integer(), nullable=True),
    sa.Column('YFRP_id', sa.Integer(), nullable=True),
    sa.Column('AM_id', sa.Integer(), nullable=True),
    sa.Column('Addr_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AM_id'], ['Managers.id'], ),
    sa.ForeignKeyConstraint(['Addr_id'], ['Addresses.id'], ),
    sa.ForeignKeyConstraint(['SoldTo_id'], ['Customers.id'], ),
    sa.ForeignKeyConstraint(['YFRP_id'], ['YFRP.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Shipto_AM_id'), 'Shipto', ['AM_id'], unique=False)
    op.create_index(op.f('ix_Shipto_Addr_id'), 'Shipto', ['Addr_id'], unique=False)
    op.create_index(op.f('ix_Shipto_ShipTo'), 'Shipto', ['ShipTo'], unique=True)
    op.create_index(op.f('ix_Shipto_SoldTo_id'), 'Shipto', ['SoldTo_id'], unique=False)
    op.create_index(op.f('ix_Shipto_YFRP_id'), 'Shipto', ['YFRP_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('comp_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_comp_id'), 'users', ['comp_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderN', sa.String(), nullable=False),
    sa.Column('Ord_type_id', sa.Integer(), nullable=False),
    sa.Column('Order_date', sa.Date(), nullable=False),
    sa.Column('Soldto_id', sa.Integer(), nullable=False),
    sa.Column('Shipto_id', sa.Integer(), nullable=False),
    sa.Column('Plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Ord_type_id'], ['OrderType.id'], ),
    sa.ForeignKeyConstraint(['Plant_id'], ['Plant.id'], ),
    sa.ForeignKeyConstraint(['Shipto_id'], ['Shipto.id'], ),
    sa.ForeignKeyConstraint(['Soldto_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Orders_OrderN'), 'Orders', ['OrderN'], unique=True)
    op.create_table('Prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Table_id', sa.Integer(), nullable=False),
    sa.Column('PriceType_id', sa.Integer(), nullable=False),
    sa.Column('ValidFrom', sa.Date(), nullable=False),
    sa.Column('ValidTo', sa.Date(), nullable=False),
    sa.Column('Hier_id', sa.Integer(), nullable=True),
    sa.Column('Soldto_id', sa.Integer(), nullable=True),
    sa.Column('Shipto_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Numeric(), nullable=True),
    sa.Column('PriceCurr', sa.String(), nullable=False),
    sa.Column('PricingUnit', sa.Integer(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Hier_id'], ['PriceHierarchy.id'], ),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], ),
    sa.ForeignKeyConstraint(['PriceType_id'], ['PriceType.id'], ),
    sa.ForeignKeyConstraint(['Shipto_id'], ['Shipto.id'], ),
    sa.ForeignKeyConstraint(['Soldto_id'], ['Customers.id'], ),
    sa.ForeignKeyConstraint(['Table_id'], ['PriceTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('InvoiceN', sa.String(), nullable=True),
    sa.Column('Invoice_date', sa.Date(), nullable=False),
    sa.Column('Inv_type_id', sa.Integer(), nullable=True),
    sa.Column('Order_id', sa.Integer(), nullable=False),
    sa.Column('Delivery_id', sa.Integer(), nullable=True),
    sa.Column('SoldTo_id', sa.Integer(), nullable=False),
    sa.Column('ShipTo_id', sa.Integer(), nullable=False),
    sa.Column('Plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Delivery_id'], ['Deliveries.id'], ),
    sa.ForeignKeyConstraint(['Inv_type_id'], ['InvoiceType.id'], ),
    sa.ForeignKeyConstraint(['Order_id'], ['Orders.id'], ),
    sa.ForeignKeyConstraint(['Plant_id'], ['Plant.id'], ),
    sa.ForeignKeyConstraint(['ShipTo_id'], ['Shipto.id'], ),
    sa.ForeignKeyConstraint(['SoldTo_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Invoices_Inv_type_id'), 'Invoices', ['Inv_type_id'], unique=False)
    op.create_index(op.f('ix_Invoices_InvoiceN'), 'Invoices', ['InvoiceN'], unique=True)
    op.create_index(op.f('ix_Invoices_Order_id'), 'Invoices', ['Order_id'], unique=False)
    op.create_table('open_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Order_id', sa.Integer(), nullable=False),
    sa.Column('LineItem', sa.Integer(), nullable=True),
    sa.Column('Pricing_date', sa.Date(), nullable=False),
    sa.Column('GI_date', sa.Date(), nullable=False),
    sa.Column('Act_GI_date', sa.Date(), nullable=True),
    sa.Column('Material_id', sa.Integer(), nullable=False),
    sa.Column('Ord_Status_id', sa.Integer(), nullable=True),
    sa.Column('OrderQty', sa.Numeric(), nullable=True),
    sa.Column('LineQty', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], ),
    sa.ForeignKeyConstraint(['Ord_Status_id'], ['OrderStatus.id'], ),
    sa.ForeignKeyConstraint(['Order_id'], ['Orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_order_lines_Order_id'), 'open_order_lines', ['Order_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Invoice_id', sa.Integer(), nullable=False),
    sa.Column('Pricing_date', sa.Date(), nullable=False),
    sa.Column('GI_date', sa.Date(), nullable=False),
    sa.Column('Act_GI_date', sa.Date(), nullable=True),
    sa.Column('Material_id', sa.Integer(), nullable=False),
    sa.Column('Ord_Status_id', sa.Integer(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['Invoice_id'], ['Invoices.id'], ),
    sa.ForeignKeyConstraint(['Material_id'], ['Materials.id'], ),
    sa.ForeignKeyConstraint(['Ord_Status_id'], ['OrderStatus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_Invoice_id'), 'invoice_lines', ['Invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_Invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_open_order_lines_Order_id'), table_name='open_order_lines')
    op.drop_table('open_order_lines')
    op.drop_index(op.f('ix_Invoices_Order_id'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_InvoiceN'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_Inv_type_id'), table_name='Invoices')
    op.drop_table('Invoices')
    op.drop_table('Prices')
    op.drop_index(op.f('ix_Orders_OrderN'), table_name='Orders')
    op.drop_table('Orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_comp_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_Shipto_YFRP_id'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_SoldTo_id'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_ShipTo'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_Addr_id'), table_name='Shipto')
    op.drop_index(op.f('ix_Shipto_AM_id'), table_name='Shipto')
    op.drop_table('Shipto')
    op.drop_index(op.f('ix_Materials_Status_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_SalProduct_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Producer_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Plant_id'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_Material_code'), table_name='Materials')
    op.drop_index(op.f('ix_Materials_BO_id'), table_name='Materials')
    op.drop_table('Materials')
    op.drop_index(op.f('ix_SalProducts_Sal_Prod_Code'), table_name='SalProducts')
    op.drop_index(op.f('ix_SalProducts_Family_id'), table_name='SalProducts')
    op.drop_table('SalProducts')
    op.drop_index(op.f('ix_Customers_SoldTo'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_PriceHier_id'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_PayTerm_id'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_Addr_id'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_AM_id'), table_name='Customers')
    op.drop_table('Customers')
    op.drop_index(op.f('ix_YFRP_YFRP'), table_name='YFRP')
    op.drop_index(op.f('ix_YFRP_Addr_id'), table_name='YFRP')
    op.drop_table('YFRP')
    op.drop_index(op.f('ix_ProdFamily_SubClass_id'), table_name='ProdFamily')
    op.drop_index(op.f('ix_ProdFamily_Family_Code'), table_name='ProdFamily')
    op.drop_table('ProdFamily')
    op.drop_index(op.f('ix_Managers_Sales_Grp'), table_name='Managers')
    op.drop_index(op.f('ix_Managers_STL_id'), table_name='Managers')
    op.drop_index(op.f('ix_Managers_LoB_id'), table_name='Managers')
    op.drop_table('Managers')
    op.drop_index(op.f('ix_FX_rate_FX_date'), table_name='FX_rate')
    op.drop_index(op.f('ix_FX_rate_Curr_id'), table_name='FX_rate')
    op.drop_table('FX_rate')
    op.drop_index(op.f('ix_Status_Status_code'), table_name='Status')
    op.drop_table('Status')
    op.drop_index(op.f('ix_STLs_STL'), table_name='STLs')
    op.drop_table('STLs')
    op.drop_table('Producer')
    op.drop_index(op.f('ix_ProdSubClass_Sub_Class'), table_name='ProdSubClass')
    op.drop_table('ProdSubClass')
    op.drop_table('PriceType')
    op.drop_table('PriceTable')
    op.drop_table('PriceHierarchy')
    op.drop_table('Plant')
    op.drop_index(op.f('ix_PaymentTerms_Pay_term'), table_name='PaymentTerms')
    op.drop_table('PaymentTerms')
    op.drop_index(op.f('ix_OrderType_Type_code'), table_name='OrderType')
    op.drop_table('OrderType')
    op.drop_table('OrderStatus')
    op.drop_index(op.f('ix_LoB_LoB'), table_name='LoB')
    op.drop_table('LoB')
    op.drop_index(op.f('ix_InvoiceType_Type_code'), table_name='InvoiceType')
    op.drop_table('InvoiceType')
    op.drop_index(op.f('ix_ED_To'), table_name='ED')
    op.drop_index(op.f('ix_ED_From'), table_name='ED')
    op.drop_table('ED')
    op.drop_index(op.f('ix_Deliveries_DeliveryN'), table_name='Deliveries')
    op.drop_table('Deliveries')
    op.drop_index(op.f('ix_Currency_Curr_code'), table_name='Currency')
    op.drop_table('Currency')
    op.drop_table('BOs')
    op.drop_index(op.f('ix_Addresses_Address_Code'), table_name='Addresses')
    op.drop_table('Addresses')
    # ### end Alembic commands ###
