"""customer table changed

Revision ID: ce12c85346f8
Revises: af302c659272
Create Date: 2022-06-18 15:43:14.975816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce12c85346f8'
down_revision = 'af302c659272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('Addr_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Customers_Addr_id'), 'Customers', ['Addr_id'], unique=False)
    op.create_foreign_key(None, 'Customers', 'Addresses', ['Addr_id'], ['id'])
    op.add_column('YFRP', sa.Column('Addr_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_YFRP_Addr_id'), 'YFRP', ['Addr_id'], unique=False)
    op.create_foreign_key(None, 'YFRP', 'Addresses', ['Addr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'YFRP', type_='foreignkey')
    op.drop_index(op.f('ix_YFRP_Addr_id'), table_name='YFRP')
    op.drop_column('YFRP', 'Addr_id')
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_index(op.f('ix_Customers_Addr_id'), table_name='Customers')
    op.drop_column('Customers', 'Addr_id')
    # ### end Alembic commands ###
