"""customer table changed

Revision ID: de60c2ab1b79
Revises: fd606578767e
Create Date: 2022-06-18 16:08:04.124378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de60c2ab1b79'
down_revision = 'fd606578767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('STL_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Customers_STL_id'), 'Customers', ['STL_id'], unique=False)
    op.create_foreign_key(None, 'Customers', 'STLs', ['STL_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_index(op.f('ix_Customers_STL_id'), table_name='Customers')
    op.drop_column('Customers', 'STL_id')
    # ### end Alembic commands ###
