"""customer table changed

Revision ID: fd606578767e
Revises: ce12c85346f8
Create Date: 2022-06-18 16:05:15.659677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd606578767e'
down_revision = 'ce12c85346f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('AM_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Customers_AM_id'), 'Customers', ['AM_id'], unique=False)
    op.create_foreign_key(None, 'Customers', 'Managers', ['AM_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_index(op.f('ix_Customers_AM_id'), table_name='Customers')
    op.drop_column('Customers', 'AM_id')
    # ### end Alembic commands ###
